title: Hello, I'm Ivan R. Putra
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ivan R. Putra # add your name
author-img: profile.png # add your photo
about-author: I am a web developer focusing on back-end development using Django or Laravel. Always hungry to keep learning. # add description
social-twitter:  # add your Twitter handle
social-facebook:  # add your Facebook handle
social-github: Ivanrputra # add your Github handle
social-linkedin: ivanrputra # add your Linkedin handle
social-email: ivanrputra@gmail.com # add your Email address

# Disqus
discus-identifier: ivanrputra # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
